#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Industryolog_ERP")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPersonal(Personal instance);
    partial void UpdatePersonal(Personal instance);
    partial void DeletePersonal(Personal instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.Industryolog_ERPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Personal> Personal
		{
			get
			{
				return this.GetTable<Personal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personal")]
	public partial class Personal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Personal_Id;
		
		private int _Team_Id;
		
		private string _Personal_Name;
		
		private string _Personal_Surname;
		
		private string _Personal_Job;
		
		private string _Personal_University;
		
		private int _Editors;
		
		private System.Data.Linq.Binary _Personel_Picture;
		
		private System.Nullable<int> _ADT_Id;
		
		private System.Nullable<int> _Gorev_Id;
		
		private string _Kurumsalmail;
		
		private string _Kisiselmail;
		
		private string _Telefon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonal_IdChanging(int value);
    partial void OnPersonal_IdChanged();
    partial void OnTeam_IdChanging(int value);
    partial void OnTeam_IdChanged();
    partial void OnPersonal_NameChanging(string value);
    partial void OnPersonal_NameChanged();
    partial void OnPersonal_SurnameChanging(string value);
    partial void OnPersonal_SurnameChanged();
    partial void OnPersonal_JobChanging(string value);
    partial void OnPersonal_JobChanged();
    partial void OnPersonal_UniversityChanging(string value);
    partial void OnPersonal_UniversityChanged();
    partial void OnEditorsChanging(int value);
    partial void OnEditorsChanged();
    partial void OnPersonel_PictureChanging(System.Data.Linq.Binary value);
    partial void OnPersonel_PictureChanged();
    partial void OnADT_IdChanging(System.Nullable<int> value);
    partial void OnADT_IdChanged();
    partial void OnGorev_IdChanging(System.Nullable<int> value);
    partial void OnGorev_IdChanged();
    partial void OnKurumsalmailChanging(string value);
    partial void OnKurumsalmailChanged();
    partial void OnKisiselmailChanging(string value);
    partial void OnKisiselmailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public Personal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Personal_Id
		{
			get
			{
				return this._Personal_Id;
			}
			set
			{
				if ((this._Personal_Id != value))
				{
					this.OnPersonal_IdChanging(value);
					this.SendPropertyChanging();
					this._Personal_Id = value;
					this.SendPropertyChanged("Personal_Id");
					this.OnPersonal_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team_Id", DbType="Int NOT NULL")]
		public int Team_Id
		{
			get
			{
				return this._Team_Id;
			}
			set
			{
				if ((this._Team_Id != value))
				{
					this.OnTeam_IdChanging(value);
					this.SendPropertyChanging();
					this._Team_Id = value;
					this.SendPropertyChanged("Team_Id");
					this.OnTeam_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Personal_Name
		{
			get
			{
				return this._Personal_Name;
			}
			set
			{
				if ((this._Personal_Name != value))
				{
					this.OnPersonal_NameChanging(value);
					this.SendPropertyChanging();
					this._Personal_Name = value;
					this.SendPropertyChanged("Personal_Name");
					this.OnPersonal_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_Surname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Personal_Surname
		{
			get
			{
				return this._Personal_Surname;
			}
			set
			{
				if ((this._Personal_Surname != value))
				{
					this.OnPersonal_SurnameChanging(value);
					this.SendPropertyChanging();
					this._Personal_Surname = value;
					this.SendPropertyChanged("Personal_Surname");
					this.OnPersonal_SurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_Job", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Personal_Job
		{
			get
			{
				return this._Personal_Job;
			}
			set
			{
				if ((this._Personal_Job != value))
				{
					this.OnPersonal_JobChanging(value);
					this.SendPropertyChanging();
					this._Personal_Job = value;
					this.SendPropertyChanged("Personal_Job");
					this.OnPersonal_JobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_University", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Personal_University
		{
			get
			{
				return this._Personal_University;
			}
			set
			{
				if ((this._Personal_University != value))
				{
					this.OnPersonal_UniversityChanging(value);
					this.SendPropertyChanging();
					this._Personal_University = value;
					this.SendPropertyChanged("Personal_University");
					this.OnPersonal_UniversityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editors", DbType="Int NOT NULL")]
		public int Editors
		{
			get
			{
				return this._Editors;
			}
			set
			{
				if ((this._Editors != value))
				{
					this.OnEditorsChanging(value);
					this.SendPropertyChanging();
					this._Editors = value;
					this.SendPropertyChanged("Editors");
					this.OnEditorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personel_Picture", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Personel_Picture
		{
			get
			{
				return this._Personel_Picture;
			}
			set
			{
				if ((this._Personel_Picture != value))
				{
					this.OnPersonel_PictureChanging(value);
					this.SendPropertyChanging();
					this._Personel_Picture = value;
					this.SendPropertyChanged("Personel_Picture");
					this.OnPersonel_PictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADT_Id", DbType="Int")]
		public System.Nullable<int> ADT_Id
		{
			get
			{
				return this._ADT_Id;
			}
			set
			{
				if ((this._ADT_Id != value))
				{
					this.OnADT_IdChanging(value);
					this.SendPropertyChanging();
					this._ADT_Id = value;
					this.SendPropertyChanged("ADT_Id");
					this.OnADT_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorev_Id", DbType="Int")]
		public System.Nullable<int> Gorev_Id
		{
			get
			{
				return this._Gorev_Id;
			}
			set
			{
				if ((this._Gorev_Id != value))
				{
					this.OnGorev_IdChanging(value);
					this.SendPropertyChanging();
					this._Gorev_Id = value;
					this.SendPropertyChanged("Gorev_Id");
					this.OnGorev_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kurumsalmail", DbType="NVarChar(100)")]
		public string Kurumsalmail
		{
			get
			{
				return this._Kurumsalmail;
			}
			set
			{
				if ((this._Kurumsalmail != value))
				{
					this.OnKurumsalmailChanging(value);
					this.SendPropertyChanging();
					this._Kurumsalmail = value;
					this.SendPropertyChanged("Kurumsalmail");
					this.OnKurumsalmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kisiselmail", DbType="NVarChar(100)")]
		public string Kisiselmail
		{
			get
			{
				return this._Kisiselmail;
			}
			set
			{
				if ((this._Kisiselmail != value))
				{
					this.OnKisiselmailChanging(value);
					this.SendPropertyChanging();
					this._Kisiselmail = value;
					this.SendPropertyChanged("Kisiselmail");
					this.OnKisiselmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(11)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
